import { Product } from '@/types/product';

export const products: Product[] = [
  { id:'new1',slug:'italian-summer-linen',name:'Italian Summer Linen',shortDescription:'Mediterranean style',description:'Classic Italian summer styling with flowing linen pieces.',category:'Clothing',gender:'Unisex',price:12890,rating:5,reviews:42,image:'/images/new-arrivals/Italian Summer Linen Style for Men.jpeg',images:['/images/new-arrivals/Italian Summer Linen Style for Men.jpeg'],colors:['Cream','White'],sizes:['S','M','L','XL'],material:'100% linen',stock:15,styleOrigin:'Italian',occasion:'Smart Casual',isNew:true },
  { id:'new2',slug:'cozy-korean-casual',name:'Cozy Korean Casual',shortDescription:'Soft comfort style',description:'Effortless Korean-inspired casual style with comfortable layers.',category:'Clothing',gender:'Unisex',price:9990,rating:4.9,reviews:38,image:'/images/new-arrivals/Cozy Korean Casual Outfit 🤍.jpeg',images:['/images/new-arrivals/Cozy Korean Casual Outfit 🤍.jpeg'],colors:['Beige','White'],sizes:['XS','S','M','L'],material:'Cotton blend',stock:18,styleOrigin:'Korean',occasion:'Streetwear',isNew:true },
  { id:'new3',slug:'resort-green-shirt',name:'Dark Green Resort Shirt',shortDescription:'Statement summer',description:'Bold resort shirt in deep green for confident summer styling.',category:'Clothing',gender:'Men',price:8490,rating:4.8,reviews:31,image:'/images/new-arrivals/Dark Green Resort Shirt Outfit Inspiration for Effortless Summer Style.jpeg',images:['/images/new-arrivals/Dark Green Resort Shirt Outfit Inspiration for Effortless Summer Style.jpeg'],colors:['Dark Green','Sage'],sizes:['S','M','L','XL'],material:'Resort cotton',stock:12,styleOrigin:'Italian',occasion:'Smart Casual',isNew:true },
  { id:'new4',slug:'effortless-street',name:'Effortless Street Style',shortDescription:'Modern casual ensemble',description:'Contemporary street style combining comfort with sophistication.',category:'Clothing',gender:'Unisex',price:10690,rating:4.9,reviews:45,image:'/images/new-arrivals/Effortless Street Style Outfit 🤎✨.jpeg',images:['/images/new-arrivals/Effortless Street Style Outfit 🤎✨.jpeg'],colors:['Chocolate','Cream'],sizes:['S','M','L','XL'],material:'Mixed materials',stock:14,styleOrigin:'Contemporary',occasion:'Streetwear',isNew:true },
  { id:'new5',slug:'chic-italian-outfit',name:'Chic Italian Getaway',shortDescription:'Vacation ready style',description:'Perfect Italian vacation outfit with refined tailoring and elegance.',category:'Clothing',gender:'Women',price:11990,rating:5,reviews:35,image:'/images/new-arrivals/17+ Chic Italian Summer Outfit Ideas For Your Next Getaway.jpeg',images:['/images/new-arrivals/17+ Chic Italian Summer Outfit Ideas For Your Next Getaway.jpeg'],colors:['Blue','White'],sizes:['XS','S','M','L'],material:'Cotton linen blend',stock:16,styleOrigin:'Italian',occasion:'Formal',isNew:true },
  { id:'new6',slug:'blue-check-korean',name:'Blue Check Korean Shirt',shortDescription:'Casual streetwear',description:'Casual Korean-style shirt outfit with modern proportions.',category:'Clothing',gender:'Men',price:7890,rating:4.7,reviews:28,image:'/images/new-arrivals/Blue Check Shirt Outfit for Men _ Casual Korean Streetwear Style.jpeg',images:['/images/new-arrivals/Blue Check Shirt Outfit for Men _ Casual Korean Streetwear Style.jpeg'],colors:['Blue','White'],sizes:['S','M','L','XL'],material:'Cotton poplin',stock:19,styleOrigin:'Korean',occasion:'Streetwear',isNew:true },
  { id:'new7',slug:'effortless-linen',name:'Effortless Summer Linen',shortDescription:'Trendy summer outfit',description:'Comfortable linen outfit perfect for summer adventures.',category:'Clothing',gender:'Unisex',price:9490,rating:4.8,reviews:32,image:'/images/new-arrivals/Effortless Summer Linen Outfit for Boys_ trendy outfit ideas 2026.jpeg',images:['/images/new-arrivals/Effortless Summer Linen Outfit for Boys_ trendy outfit ideas 2026.jpeg'],colors:['Beige','Cream'],sizes:['S','M','L','XL'],material:'100% linen',stock:17,styleOrigin:'Contemporary',occasion:'Smart Casual',isNew:true },
  { id:'new8',slug:'italian-vibes',name:'Italian Vibes Set',shortDescription:'Casual Italian style',description:'Relaxed Italian casual wear with Mediterranean charm.',category:'Clothing',gender:'Unisex',price:8990,rating:4.9,reviews:40,image:'/images/new-arrivals/Italian Vibezzzz 💸🍕.jpeg',images:['/images/new-arrivals/Italian Vibezzzz 💸🍕.jpeg'],colors:['Cream','Brown'],sizes:['S','M','L','XL'],material:'Linen cotton blend',stock:13,styleOrigin:'Italian',occasion:'Smart Casual',isNew:true },
  { id:'new9',slug:'japanese-minimal',name:'Japanese Street Fashion',shortDescription:'Minimalist trendy',description:'Minimal and trendy Japanese street style outfit.',category:'Clothing',gender:'Unisex',price:10290,rating:4.9,reviews:36,image:'/images/new-arrivals/Japanese Street Fashion Outfit – Minimal & Trendy_.jpeg',images:['/images/new-arrivals/Japanese Street Fashion Outfit – Minimal & Trendy_.jpeg'],colors:['Black','White'],sizes:['XS','S','M','L','XL'],material:'Premium cotton',stock:11,styleOrigin:'Japanese',occasion:'Streetwear',isNew:true },
  { id:'new10',slug:'korean-brown-stripe',name:'Korean Brown Stripe',shortDescription:'Casual streetwear',description:'Casual Korean outfit with brown striped shirt styling.',category:'Clothing',gender:'Men',price:7590,rating:4.7,reviews:29,image:'/images/new-arrivals/Korean Men Casual Outfit – Brown Striped Shirt Style.jpeg',images:['/images/new-arrivals/Korean Men Casual Outfit – Brown Striped Shirt Style.jpeg'],colors:['Brown','Cream'],sizes:['S','M','L','XL'],material:'Cotton blend',stock:14,styleOrigin:'Korean',occasion:'Streetwear',isNew:true },
  { id:'new11',slug:'korean-casual-idea',name:'Korean Casual Idea',shortDescription:'Modern casual',description:'Modern Korean casual outfit with contemporary styling.',category:'Clothing',gender:'Unisex',price:8890,rating:4.8,reviews:33,image:'/images/new-arrivals/korean outfit idea.jpeg',images:['/images/new-arrivals/korean outfit idea.jpeg'],colors:['Multi','Neutral'],sizes:['XS','S','M','L'],material:'Cotton mix',stock:12,styleOrigin:'Korean',occasion:'Casual',isNew:true },
  { id:'new12',slug:'men-fashion-look',name:'Men Fashion Look',shortDescription:'Fashion forward',description:'Contemporary men\'s fashion statement outfit.',category:'Clothing',gender:'Men',price:11890,rating:5,reviews:44,image:'/images/new-arrivals/MEN FASHION.jpeg',images:['/images/new-arrivals/MEN FASHION.jpeg'],colors:['Navy','Cream'],sizes:['S','M','L','XL'],material:'Premium blend',stock:10,styleOrigin:'Contemporary',occasion:'Smart Casual',isNew:true },
  { id:'new13',slug:'minimal-campus-chic',name:'Minimal Campus Chic',shortDescription:'University style',description:'Chic minimal outfit perfect for campus or casual outings.',category:'Clothing',gender:'Women',price:7290,rating:4.7,reviews:26,image:'/images/new-arrivals/Minimal Campus Chic 🤍📚.jpeg',images:['/images/new-arrivals/Minimal Campus Chic 🤍📚.jpeg'],colors:['White','Beige'],sizes:['XS','S','M','L'],material:'Cotton jersey',stock:15,styleOrigin:'Scandinavian',occasion:'Casual',isNew:true },
  { id:'new14',slug:'old-money-style',name:'Old Money Style',shortDescription:'Luxury classic',description:'Timeless old money aesthetic with refined tailoring.',category:'Clothing',gender:'Unisex',price:14990,rating:5,reviews:51,image:'/images/new-arrivals/Old money Style.jpeg',images:['/images/new-arrivals/Old money Style.jpeg'],colors:['Navy','Camel','Cream'],sizes:['S','M','L','XL'],material:'Premium wool blend',stock:8,styleOrigin:'British',occasion:'Formal',isNew:true },
  { id:'new15',slug:'old-money-summer',name:'Old Money Summer',shortDescription:'Luxury summer',description:'Summer version of old money aesthetic with premium materials.',category:'Clothing',gender:'Men',price:13890,rating:4.9,reviews:47,image:'/images/new-arrivals/Old Money Summer Outfit for Men 🍂 _ Minimal Luxury Street Style 2026.jpeg',images:['/images/new-arrivals/Old Money Summer Outfit for Men 🍂 _ Minimal Luxury Street Style 2026.jpeg'],colors:['Camel','Cream','Brown'],sizes:['S','M','L','XL'],material:'Luxury linen blend',stock:9,styleOrigin:'British',occasion:'Smart Casual',isNew:true },
  { id:'new16',slug:'relaxed-trousers',name:'Relaxed Fit Trousers',shortDescription:'Comfort tailoring',description:'Modern relaxed fit trousers with tailored comfort.',category:'Clothing',gender:'Men',price:6990,rating:4.8,reviews:34,image:'/images/new-arrivals/Relaxed Fit Mens Trousers.jpeg',images:['/images/new-arrivals/Relaxed Fit Mens Trousers.jpeg'],colors:['Khaki','Stone','Navy'],sizes:['30','32','34','36'],material:'Cotton blend twill',stock:20,styleOrigin:'Contemporary',occasion:'Smart Casual',isNew:true },
  { id:'new17',slug:'sage-green-polo',name:'Sage Green Polo Set',shortDescription:'Refined casual',description:'Classic sage green polo with cream trousers for refined casual.',category:'Clothing',gender:'Men',price:8690,rating:4.9,reviews:39,image:'/images/new-arrivals/Sage Green Polo Shirt and Cream Trousers Outfit for Men.jpeg',images:['/images/new-arrivals/Sage Green Polo Shirt and Cream Trousers Outfit for Men.jpeg'],colors:['Sage Green','Cream'],sizes:['S','M','L','XL'],material:'Cotton knit',stock:14,styleOrigin:'Italian',occasion:'Smart Casual',isNew:true },
  { id:'new18',slug:'viral-luxury',name:'Viral Luxury Streetwear',shortDescription:'Trending luxury',description:'Trending casual luxury streetwear outfit for 2026.',category:'Clothing',gender:'Men',price:10890,rating:4.9,reviews:52,image:'/images/new-arrivals/Viral Men\'s Summer Outfit 2026 _ Casual Luxury Streetwear Ideas You Need to Try.jpeg',images:['/images/new-arrivals/Viral Men\'s Summer Outfit 2026 _ Casual Luxury Streetwear Ideas You Need to Try.jpeg'],colors:['Pinstripe','Denim','White'],sizes:['S','M','L','XL'],material:'Premium cotton',stock:11,styleOrigin:'Contemporary',occasion:'Streetwear',isNew:true },
  { id:'new19',slug:'korean-sweater',name:'Korean Sweater Style',shortDescription:'Cozy knit wear',description:'Korean sweater style with modern silhouette.',category:'Clothing',gender:'Unisex',price:7890,rating:4.7,reviews:30,image:'/images/new-arrivals/【ONELYC1NS】Korean version of sweater na1641.jpeg',images:['/images/new-arrivals/【ONELYC1NS】Korean version of sweater na1641.jpeg'],colors:['Neutral','Warm'],sizes:['S','M','L','XL'],material:'Knit blend',stock:16,styleOrigin:'Korean',occasion:'Casual',isNew:true },
  { id:'new20',slug:'flare-skirt-coord',name:'Flare Skirt Coordination',shortDescription:'Modern skirt look',description:'Modern coordination with flare skirt styling.',category:'Clothing',gender:'Women',price:8290,rating:4.8,reviews:31,image:'/images/new-arrivals/カジュアル派の【バサッとフレアスカート】コーデ8選｜今っぽくかっこよく仕上げたい！ _ Oggi_jp.jpeg',images:['/images/new-arrivals/カジュアル派の【バサッとフレアスカート】コーデ8選｜今っぽくかっこよく仕上げたい！ _ Oggi_jp.jpeg'],colors:['Multi','Neutral'],sizes:['XS','S','M','L'],material:'Cotton blend',stock:13,styleOrigin:'Japanese',occasion:'Smart Casual',isNew:true },
  { id:'new21',slug:'kio-luxury',name:'KIO Luxury Outfit',shortDescription:'Premium styling',description:'Premium luxury outfit styling for modern elegance.',category:'Clothing',gender:'Unisex',price:12390,rating:5,reviews:43,image:'/images/new-arrivals/𝐊𝐈𝐎.jpeg',images:['/images/new-arrivals/𝐊𝐈𝐎.jpeg'],colors:['Neutral','Premium'],sizes:['S','M','L','XL'],material:'Luxury blend',stock:10,styleOrigin:'Contemporary',occasion:'Formal',isNew:true },
  { id:'new22',slug:'model-pose-14',name:'Professional Model Look',shortDescription:'Editorial styling',description:'Professional editorial styling outfit for refined elegance.',category:'Clothing',gender:'Unisex',price:9890,rating:4.9,reviews:37,image:'/images/new-arrivals/13440498883859832.jpeg',images:['/images/new-arrivals/13440498883859832.jpeg'],colors:['Neutral','Earthy'],sizes:['XS','S','M','L'],material:'Premium cotton',stock:12,styleOrigin:'Contemporary',occasion:'Smart Casual',isNew:true },
  { id:'new23',slug:'street-style-36',name:'Street Style Essential',shortDescription:'Urban casual',description:'Essential street style outfit for urban fashion.',category:'Clothing',gender:'Unisex',price:8590,rating:4.8,reviews:35,image:'/images/new-arrivals/844493674045206.jpeg',images:['/images/new-arrivals/844493674045206.jpeg'],colors:['Neutral','Urban'],sizes:['S','M','L','XL'],material:'Cotton mix',stock:14,styleOrigin:'Contemporary',occasion:'Streetwear',isNew:true },
  { id:'new24',slug:'candid-moment-78',name:'Candid Street Moment',shortDescription:'Casual authentic',description:'Authentic candid moment street style outfit.',category:'Clothing',gender:'Unisex',price:7790,rating:4.7,reviews:27,image:'/images/new-arrivals/17451517303522631.jpeg',images:['/images/new-arrivals/17451517303522631.jpeg'],colors:['Neutral','Casual'],sizes:['S','M','L','XL'],material:'Everyday cotton',stock:15,styleOrigin:'Contemporary',occasion:'Casual',isNew:true },
  { id:'p1',slug:'glen-brushed-overshirt',name:'Glen Brushed Overshirt',shortDescription:'Soft brushed twill',description:'An easy structured layer cut from a substantial brushed twill. Designed for changeable days and years of wear.',category:'Clothing',gender:'Unisex',price:7490,rating:4.9,reviews:84,image:'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80'],colors:['Highland Red','Charcoal'],sizes:['S','M','L','XL'],material:'100% cotton twill',stock:18,styleOrigin:'Scottish',occasion:'Outdoor',isNew:true },
  { id:'p2',slug:'moray-lambswool-crew',name:'Moray Lambswool Crew',shortDescription:'Lightweight warm knit',description:'A clean crewneck in naturally insulating lambswool, with a relaxed fit for thoughtful daily layering.',category:'Clothing',gender:'Unisex',price:5890,rating:4.8,reviews:129,image:'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=80'],colors:['Oat','Navy'],sizes:['S','M','L','XL'],material:'100% lambswool',stock:12,styleOrigin:'Scottish',occasion:'Casual',isNew:true },
  { id:'p3',slug:'skye-relaxed-trouser',name:'Skye Relaxed Trouser',shortDescription:'Italian cotton canvas',description:'The trouser that brings ease to tailoring. Straight through the leg, softly structured at the waist.',category:'Clothing',gender:'Men',price:6290,rating:4.7,reviews:61,image:'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80'],colors:['Moss','Stone'],sizes:['30','32','34','36'],material:'98% cotton, 2% elastane',stock:20,styleOrigin:'Scottish',occasion:'Smart Casual' },
  { id:'p4',slug:'cairn-leather-boot',name:'Cairn Leather Boot',shortDescription:'Weather-ready leather',description:'A quietly capable boot in oiled leather, finished with a durable rubber sole for city and country alike.',category:'Shoes',gender:'Unisex',price:8990,rating:4.9,reviews:201,image:'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80'],colors:['Chestnut','Black'],sizes:['39','40','41','42','43'],material:'Full-grain leather',stock:7,styleOrigin:'Scottish',occasion:'Outdoor',isBestSeller:true },
  { id:'p5',slug:'kintyre-oxford-shirt',name:'Kintyre Oxford Shirt',shortDescription:'Classic Oxford weave',description:'An uncomplicated, precisely-cut shirt that is comfortable enough for the everyday.',category:'Clothing',gender:'Men',price:4690,rating:4.6,reviews:47,image:'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80'],colors:['Sky','White'],sizes:['S','M','L','XL'],material:'100% organic cotton',stock:22,styleOrigin:'Contemporary',occasion:'Smart Casual' },
  { id:'p6',slug:'tay-tartan-scarf',name:'Tay Tartan Scarf',shortDescription:'Woven heritage check',description:'A finely woven scarf carrying a restrained tartan check in seasonal tones.',category:'Accessories',gender:'Unisex',price:3290,rating:4.8,reviews:95,image:'https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&w=900&q=80'],colors:['Heather Check'],sizes:['One size'],material:'70% wool, 30% silk',stock:34,styleOrigin:'Scottish',occasion:'Casual',isBestSeller:true },
  { id:'p7',slug:'orkney-utility-jacket',name:'Orkney Utility Jacket',shortDescription:'Water-resistant field layer',description:'A refined utility jacket that takes its practicality from the coast and its shape from modern tailoring.',category:'Clothing',gender:'Women',price:10490,rating:4.9,reviews:39,image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80'],colors:['Navy','Lichen'],sizes:['XS','S','M','L'],material:'Water-resistant cotton blend',stock:10,styleOrigin:'Scottish',occasion:'Outdoor',isNew:true },
  { id:'p8',slug:'fife-wool-beanie',name:'Fife Wool Beanie',shortDescription:'Ribbed merino wool',description:'A close ribbed beanie with a considered depth and naturally warm merino yarn.',category:'Accessories',gender:'Unisex',price:2390,rating:4.7,reviews:73,image:'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=900&q=80'],colors:['Oat','Navy','Red'],sizes:['One size'],material:'100% merino wool',stock:42,styleOrigin:'Scottish',occasion:'Casual' },
  { id:'p9',slug:'milan-relaxed-blazer',name:'Milan Relaxed Blazer',shortDescription:'Italian wool tailoring',description:'An unstructured blazer with a soft shoulder and effortless drape. A formal piece that never feels stiff.',category:'Clothing',gender:'Men',price:14990,rating:4.9,reviews:44,image:'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80'],colors:['Espresso','Navy'],sizes:['S','M','L','XL'],material:'Italian wool blend',stock:11,styleOrigin:'Italian',occasion:'Formal',isNew:true },
  { id:'p10',slug:'como-pleated-trouser',name:'Como Pleated Trouser',shortDescription:'Tailored wide-leg fit',description:'Double-pleat trousers in a smooth twill with room through the leg and an elevated finish.',category:'Clothing',gender:'Men',price:7990,rating:4.8,reviews:33,image:'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=900&q=80'],colors:['Stone','Black'],sizes:['30','32','34','36'],material:'Wool-viscose twill',stock:16,styleOrigin:'Italian',occasion:'Formal' },
  { id:'p11',slug:'sorrento-knit-polo',name:'Sorrento Knit Polo',shortDescription:'Textured summer knit',description:'A refined short-sleeve polo inspired by Italian summer evenings. Soft texture, clean collar, relaxed confidence.',category:'Clothing',gender:'Men',price:6490,rating:4.8,reviews:68,image:'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?auto=format&fit=crop&w=900&q=80'],colors:['Cream','Olive'],sizes:['S','M','L','XL'],material:'Cotton knit',stock:27,styleOrigin:'Italian',occasion:'Smart Casual' },
  { id:'p12',slug:'seoul-boxy-shirt',name:'Seoul Boxy Shirt',shortDescription:'Crisp oversized cotton',description:'A proportion-led poplin shirt with a dropped shoulder and cropped, boxy body.',category:'Clothing',gender:'Unisex',price:5290,rating:4.7,reviews:91,image:'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=80'],colors:['White','Ink'],sizes:['XS','S','M','L'],material:'Crisp cotton poplin',stock:35,styleOrigin:'Korean',occasion:'Streetwear',isNew:true },
  { id:'p13',slug:'han-ribbed-cardigan',name:'Han Ribbed Cardigan',shortDescription:'Soft cropped cardigan',description:'A clean ribbed cardigan with a close silhouette. Made for layering, designed to be worn alone too.',category:'Clothing',gender:'Women',price:5690,rating:4.8,reviews:52,image:'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=80'],colors:['Graphite','Cloud'],sizes:['XS','S','M','L'],material:'Viscose blend rib',stock:24,styleOrigin:'Korean',occasion:'Casual' },
  { id:'p14',slug:'gangnam-wide-denim',name:'Gangnam Wide Denim',shortDescription:'Relaxed washed denim',description:'A full-length, wide jean with an easy low-rise fit and a deliberate faded wash.',category:'Clothing',gender:'Unisex',price:6990,rating:4.6,reviews:110,image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80'],colors:['Indigo','Faded Blue'],sizes:['28','30','32','34','36'],material:'100% cotton denim',stock:31,styleOrigin:'Korean',occasion:'Streetwear' },
  { id:'p15',slug:'kyoto-indigo-jacket',name:'Kyoto Indigo Jacket',shortDescription:'Japanese selvedge denim',description:'A minimal workwear jacket cut in deep indigo selvedge denim. Durable, purposeful and quietly striking.',category:'Clothing',gender:'Unisex',price:11990,rating:5,reviews:38,image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80'],colors:['Indigo'],sizes:['S','M','L','XL'],material:'Japanese selvedge denim',stock:9,styleOrigin:'Japanese',occasion:'Casual',isBestSeller:true },
  { id:'p16',slug:'nara-camp-collar-shirt',name:'Nara Camp Collar Shirt',shortDescription:'Draped textured shirt',description:'A relaxed camp collar shirt made with a subtle woven texture and an open, easy neckline.',category:'Clothing',gender:'Unisex',price:6490,rating:4.8,reviews:49,image:'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=900&q=80'],colors:['Sand','Ink'],sizes:['S','M','L','XL'],material:'Textured rayon blend',stock:19,styleOrigin:'Japanese',occasion:'Casual' },
  { id:'p17',slug:'tokyo-technical-trouser',name:'Tokyo Technical Trouser',shortDescription:'Tapered utility trouser',description:'A lightweight technical trouser with a tapered shape, adjustable hem and travel-ready stretch.',category:'Clothing',gender:'Unisex',price:7590,rating:4.7,reviews:66,image:'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=900&q=80'],colors:['Black','Olive'],sizes:['S','M','L','XL'],material:'Technical nylon stretch',stock:17,styleOrigin:'Japanese',occasion:'Streetwear' },
  { id:'p18',slug:'roma-leather-loafer',name:'Roma Leather Loafer',shortDescription:'Hand-finished leather',description:'A low-profile leather loafer with a lightly cushioned insole for formal days and relaxed evenings.',category:'Shoes',gender:'Men',price:10990,rating:4.9,reviews:74,image:'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=900&q=80'],colors:['Brown','Black'],sizes:['39','40','41','42','43'],material:'Hand-finished leather',stock:13,styleOrigin:'Italian',occasion:'Formal' },
  { id:'p19',slug:'busan-nylon-crossbody',name:'Busan Nylon Crossbody',shortDescription:'Compact everyday bag',description:'A scaled-down utility crossbody with exterior pocketing and an adjustable webbing strap.',category:'Bags',gender:'Unisex',price:4990,rating:4.7,reviews:59,image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80'],colors:['Black','Steel'],sizes:['One size'],material:'Recycled nylon',stock:29,styleOrigin:'Korean',occasion:'Streetwear' },
  { id:'p20',slug:'osaka-minimal-watch',name:'Osaka Minimal Watch',shortDescription:'Quiet everyday timepiece',description:'A pared-back steel watch with a clean dial and interchangeable woven strap.',category:'Watches',gender:'Unisex',price:12490,rating:4.8,reviews:41,image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80'],colors:['Silver','Black'],sizes:['One size'],material:'Stainless steel',stock:15,styleOrigin:'Japanese',occasion:'Smart Casual' },
];

type StyleCollection = { name: string; description: string; materials: string; colors: string; occasion: string };

const styleCollections: StyleCollection[] = [
  { name: 'Italian', description: 'Sharp tailoring and luxury Italian craftsmanship', materials: 'wool, silk, fine cotton', colors: 'camel, navy, cream, burgundy', occasion: 'Smart Casual' },
  { name: 'Japanese', description: 'Minimalist oversized silhouette with quiet detailing', materials: 'linen, cotton, denim', colors: 'black, indigo, off-white, grey', occasion: 'Casual' },
  { name: 'Korean', description: 'Soft streetwear with a pastel K-fashion vibe', materials: 'cotton blend, corduroy, knit', colors: 'pastel pink, lavender, beige, mint', occasion: 'Streetwear' },
  { name: 'American (USA)', description: 'Casual relaxed all-American cut', materials: 'denim, jersey, fleece', colors: 'red, white, blue, grey', occasion: 'Casual' },
  { name: 'Australian', description: 'Laid-back beach-city coastal style', materials: 'cotton, linen, chambray', colors: 'sand, olive, sky blue, white', occasion: 'Casual' },
  { name: 'French', description: 'Chic Parisian elegance with effortless styling', materials: 'silk, wool, crepe', colors: 'black, navy, ivory, red', occasion: 'Smart Casual' },
  { name: 'British (UK)', description: 'Classic heritage with smart-casual tailoring', materials: 'tweed, wool, houndstooth', colors: 'grey, forest green, burgundy, navy', occasion: 'Formal' },
  { name: 'Spanish', description: 'Bold vibrant style with flamenco-inspired energy', materials: 'cotton, satin, ruffled fabric', colors: 'red, black, mustard, terracotta', occasion: 'Smart Casual' },
  { name: 'German', description: 'Clean functional design with a structured minimal cut', materials: 'technical cotton, wool blend', colors: 'grey, black, white, steel blue', occasion: 'Smart Casual' },
  { name: 'Chinese', description: 'Modern fusion with traditional Chinese-inspired motifs', materials: 'silk, brocade, cotton', colors: 'red, gold, jade green, black', occasion: 'Formal' },
  { name: 'Scandinavian', description: 'Simple cozy Nordic minimalism', materials: 'wool, knit, fleece', colors: 'grey, white, muted blue, beige', occasion: 'Casual' },
  { name: 'Bohemian', description: 'Free-spirited boho style with artisanal prints', materials: 'cotton, rayon, embroidered fabric', colors: 'earthy brown, rust, turquoise, cream', occasion: 'Casual' },
  { name: 'Streetwear (Urban)', description: 'Bold graphic urban streetwear', materials: 'fleece, denim, cotton jersey', colors: 'black, neon, grey, white', occasion: 'Streetwear' },
  { name: 'Vintage / Retro', description: 'Old-school retro cuts and expressive prints', materials: 'corduroy, denim, polyester blend', colors: 'mustard, brown, faded blue, cream', occasion: 'Casual' },
  { name: 'African-inspired', description: 'Vibrant print-led style with rich textile influence', materials: 'Ankara cotton, kente fabric', colors: 'orange, green, yellow, multicolor print', occasion: 'Smart Casual' },
];

const garments = [
  { name: 'T-Shirt', price: 2990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85' },
  { name: 'Casual Shirt', price: 4690, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=85' },
  { name: 'Formal Shirt', price: 5490, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=900&q=85' },
  { name: 'Blazer', price: 12990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=85' },
  { name: 'Jacket', price: 8990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85' },
  { name: 'Denim Jacket', price: 9490, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&q=85' },
  { name: 'Jeans', price: 6490, gender: 'Unisex', sizes: ['28', '30', '32', '34', '36'], image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85' },
  { name: 'Trousers', price: 6990, gender: 'Unisex', sizes: ['28', '30', '32', '34', '36'], image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=85' },
  { name: 'Hoodie', price: 5990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85' },
  { name: 'Sweater', price: 6290, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=85' },
  { name: 'Long Coat', price: 14990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=85' },
  { name: 'Dress', price: 8990, gender: 'Women', sizes: ['XS', 'S', 'M', 'L'], image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85' },
  { name: 'Skirt', price: 4990, gender: 'Women', sizes: ['XS', 'S', 'M', 'L'], image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=900&q=85' },
  { name: 'Shorts', price: 3990, gender: 'Unisex', sizes: ['S', 'M', 'L', 'XL'], image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=85' },
] as const;

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const catalogueProducts: Product[] = styleCollections.flatMap((style, styleIndex) => garments.map((garment, garmentIndex) => {
  const colors = style.colors.split(', ');
  const productNumber = styleIndex * garments.length + garmentIndex + 21;
  const name = `${style.name} ${garment.name}`;
  return {
    id: `p${productNumber}`,
    slug: slugify(name),
    name,
    shortDescription: `${style.description} — ${garment.name.toLowerCase()}`,
    description: `A modern ${garment.name.toLowerCase()} shaped by ${style.name} design. ${style.description}. Crafted in a considered ${style.materials.split(', ')[0]} finish for an elevated everyday wardrobe.`,
    category: 'Clothing',
    gender: garment.gender,
    price: garment.price + styleIndex * 120,
    rating: Number((4.6 + ((styleIndex + garmentIndex) % 5) / 10).toFixed(1)),
    reviews: 18 + ((styleIndex * 17 + garmentIndex * 11) % 120),
    image: garment.image,
    images: [garment.image],
    colors,
    sizes: [...garment.sizes],
    material: style.materials,
    stock: 8 + ((styleIndex * 7 + garmentIndex * 3) % 34),
    styleOrigin: style.name,
    occasion: garment.name === 'Formal Shirt' || garment.name === 'Blazer' ? 'Formal' : style.occasion,
    isNew: styleIndex >= 10,
  };
}));

products.push(...catalogueProducts);
export const findProduct = (slug: string) => products.find(p => p.slug === slug);
